export const GET_RANDOM_RECIPE = 'GET_RANDOM_RECIPE';
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const SET_LOADER = 'SET_LOADER';
export const CLEAR_LOADER = 'CLEAR_LOADER';
export const GET_WEATHER_TODAY = 'GET_WEATHER_TODAY';
export const SET_HOMEPAGE = 'SET_HOMEPAGE';
// export const GET_LOCATION = 'GET_LOCATION';
export const SAVE_RECIPE_TO_FAVOURITES = 'SAVE_RECIPE_TO_FAVOURITES';